
tasks:
  - name: Client
    before: cd client
    init: |
      npm install
      clear
    command: npm run start
  - name: Server
    before: cd server
    init: |
      npm install
      clear
    command: npm run dev
    openMode: split-right


ports:
  - port: 8000
    onOpen: open-preview
  - port: 5000
    onOpen: open-preview
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - panekj.powershell
    - GitHub.vscode-pull-request-github
    - dracula-theme.theme-dracula
    - rangav.vscode-thunder-client
    - BeardedBear.beardedtheme
    - enkia.tokyo-night
